source: ./_source
destination: ./_site

timezone: Europe/Warsaw

strict_front_matter: true

include:
  - .well-known

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
